### ISSUE TITLE
Init Git

### ISSUE THREAD

**Issue by EmilIvanov** [anton-tsarev-mm/node-js#2]
# Tasks
- [ ] initialize a git repository locally
- [ ] add a `README.md` file
- [ ] commit the project source
- [ ] set the `main` branch
- [ ] add the remote GitHub repository
- [ ] push the source to the remote repository

**P.S.:** This is just a breakdown of the instructions on the newly created repository [page](https://github.com/anton-tsarev-mm/node-js)
