### ISSUE TITLE
Generate a task resource

### ISSUE THREAD

**Issue by EmilIvanov** [anton-tsarev-mm/node-js#3]
# Description
Using the Nest CLI, generate a new resource that will represent the tasks in a To-Do app.

# Tasks
- [ ] using the Nest CLI, generate a resource named `task`
- [ ] choose `REST API` for the transport layer question
- [ ] choose `Y` to generate CRUD entry points
- [ ] inspect the generated code
- [ ] call each generated endpoint using your favorite HTTP client

# Resources
 - [CRUD Generator](https://docs.nestjs.com/recipes/crud-generator#generating-a-new-resource)
