### ISSUE TITLE
Create a docker compose file for PostgreSQL

### ISSUE THREAD

**Issue by EmilIvanov** [anton-tsarev-mm/node-js#6]
# Description
In order to spin up easily a database locally, create docker compose file with a PostgreSQL 15 service.

# Prerequisites
- [x] setup Docker locally, guide [here](https://docs.docker.com/engine/install/)

# Tasks
- [x] create a `docker-compose.yml` file with a single `db` service, that uses a `postgres:15-alpine` image
- [x] spin up a database locally using `docker compose up -d`
- [x] verify that a connection can be established to the created database

# Notes
- [ ] discuss familiarity with `Docker` on the sync up call
