### ISSUE TITLE
Setup checks on commit

### ISSUE THREAD

**Issue by EmilIvanov** [anton-tsarev-mm/node-js#7]
# Description
In order to enforce quality of code, checks need to be configured to run before code is committed.

# Tasks
- [x] setup [husky](https://www.npmjs.com/package/husky)
- [x] setup [lint-staged](https://www.npmjs.com/package/lint-staged)
- [x] setup [commitlint](https://www.npmjs.com/package/@commitlint/cli)
- [x] configure `lint-staged` to run `eslint` on `ts` files and `prettier` on `ts` and `md` files
- [x] create a `commit-message` hook that runs commit lint
- [x] create a `pre-commit` hook that runs `lint-staged`, unit tests and e2e tests
