### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by EmilIvanov** [anton-tsarev-mm/node-js#8]
# Description
In order to keep local configuration out of source control, configure the application to be able to work with environment variables.

# Tasks
- [ ] add and configure the [@nestjs/config](https://docs.nestjs.com/techniques/configuration) module
- [ ] create a `.env.example` file and commit it to source. Add a `PORT=3000` environment variable to `.env.example`
- [ ] add `.env` to `.gitignore`
- [ ] update `main.ts` to read the port value from `.env` using the config module
